### ISSUE TITLE
No way to look notes created with "Mentioned users only" visibility in profile page

### ISSUE THREAD

**Issue by moreal** [hackers-pub/hackerspub#19]
I've created a note with `Mentioned users only` visibility without any mentions, and the note appeared in the main timeline (at `https://hackers.pub/`) like following screenshots.

![Image](https://github.com/user-attachments/assets/8d4aec1b-c234-4587-b781-bd05de36c749)
![Image](https://github.com/user-attachments/assets/612399c5-88b9-477c-b4c2-ee237a1f756c)

But, in my profile page (at `https://hackers.pub/@moreal`), the note didn't appear. I may become not able to find the note after some days.

![Image](https://github.com/user-attachments/assets/dff181a0-0b08-455d-a04c-cd688a775ddd)

You can see the note with `Mentioned users only` visibility at https://hackers.pub/@moreal/0195d7b3-d745-7613-8722-e613aa96e30d

**Comment by dahlia** [comment]
Still does it? I think it's fixed now.

**Comment by moreal** [comment]
@dahlia Sadly, I still cannot see the post at my profile page 😥

**Comment by moreal** [comment]
Maybe, it is because of `visibility` filter doesn't include `"direct"` type. Since it is unusual case, I'll investigate myself and let you know.

https://github.com/dahlia/hackerspub/blob/6b5cb313da32fb5850bc3fa3b5c0bc6d5e993406/routes/%40%5Busername%5D/notes.tsx#L149

**Comment by moreal** [comment]
As memo, I realized that notes with `Followers` visibility cannot be found too.

**Comment by dahlia** [comment]
Do you mean they are invisible on your profile page, or on your home timeline?

**Comment by moreal** [comment]
> Do you mean they are invisible on your profile page, or on your home timeline?

I mean on my profile page.

https://hackers.pub/@moreal/01961092-58cc-7921-b78d-16bc9eeadef6 note was posted with `Followers` visibility and I cannot see it in my profile page

"Total" tab:
<img width="931" alt="Image" src="https://github.com/user-attachments/assets/6e616e38-3352-422a-8d21-365df40af517" />

"Notes" tab:
<img width="881" alt="Image" src="https://github.com/user-attachments/assets/bb425bd3-b72c-47c0-82ea-57adc5dd8b79" />

"Notes with replies" tab:
<img width="885" alt="Image" src="https://github.com/user-attachments/assets/e22e8b9a-22bf-463f-b2d8-5f7b6537ebed" />

**Comment by dahlia** [comment]
Ah, that's an already acknowledged problem:

https://github.com/hackers-pub/hackerspub/blob/421c4b43bedde76a6aec6b9816bd9e9c5610752b/routes/%40%5Busername%5D/index.tsx#L387

As you can see above, it only shows `"public"` and `"unlisted"` (quiet public) posts on the profile page. I'm going to fix it soon.

**Comment by moreal** [comment]
Ah, it works now, thank you!
